#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram>
# Description: Auto compile
#
name: "Auto compile with OpenWrt SDK for Main"
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
    branches:
      - '${{ github.ref_name }}'
    paths:
      - 'luci-theme-hj/Makefile'
env:
  TZ: Asia/Jakarta
  rakitiw: ${{ github.repository }}

jobs:
  job_check:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      rakitiw_version: ${{ steps.check_version.outputs.latest_version }}
      has_update: ${{ steps.check_version.outputs.has_update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Check version
        id: check_version
        env:
          url_release: https://api.github.com/repos/${{ env.rakitiw }}/releases/latest
        run: |
          cd luci-theme-hj
          latest_version=$(awk -F ':=' '/PKG_VERSION|PKG_RELEASE/ {print $2}' Makefile | sed ':a;N;s/\n$//;s/\n/-/;ba')
          latest_release=$(wget -qO- -t1 -T2 ${{env.url_release}} | awk -F '"' '/tag_name/{print $4}')
          has_update=$([ "${latest_version}" != "${latest_release}" ] && echo true || echo false)
          echo "::set-output name=latest_version::${latest_version}"
          echo "::set-output name=has_update::${has_update}"
          echo "latest_version: ${latest_version}"
          echo "latest_release: ${latest_release}"
          echo "has_update: ${has_update}"

      - name: Generate new tag & release
        if: steps.check_version.outputs.has_update == 'true'
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.check_version.outputs.latest_version}}
          target_commitish: ${{ github.ref_name }}
          prerelease: ${{steps.check_version.outputs.prerelease}}
          body: |
            ## :mega:Update content
            
  build_ipk:
    needs: job_check
    outputs:
      rakitiw_version: ${{ needs.job_check.outputs.rakitiw_version }}
      has_update: ${{ needs.job_check.outputs.rakitiw_version }}
    permissions:
      contents: write
    name: Build Rakitiw
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 21.02.7
          - 23.05.0
          - 24.10.0
        arch:
          - x86_64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Preparing Rakitiw
        run: |
          echo ""
          mkdir feeds artifacts
          cp -rf ./luci-theme-hj ./feeds

      - name: Building Luci Rakitiw
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feeds
          PACKAGES: luci-theme-hj
          NO_SHFMT_CHECK: 1

      - name: Delivering Package
        uses: actions/upload-artifact@v4
        with:
          name: luci-theme-hj-${{ matrix.release }}_${{ matrix.arch }}
          path: ${{ github.workspace }}/artifacts/bin/packages/${{ matrix.arch }}/action/luci-theme*

  push_packages:
    needs: build_ipk
    name: Push Packages to Release
    permissions:
      contents: write  # To push a branch
    runs-on: ubuntu-latest
    steps:
      - name: Download temporary artifact
        uses: actions/download-artifact@v4

      - name: Moving artifact to releases
        shell: bash
        run: |
          mkdir ./release
          cp -rf ./luci-theme-hj-21.02.7_x86_64/* ./release/luci-theme-hj_${{ needs.build_ipk.outputs.rakitiw_version }}_all_21_02.ipk
          cp -rf ./luci-theme-hj-23.05.0_x86_64/* ./release/luci-theme-hj_${{ needs.build_ipk.outputs.rakitiw_version }}_all_23_05.ipk
          cp -rf ./luci-theme-hj-24.10.0_x86_64/* ./release/luci-theme-hj_${{ needs.build_ipk.outputs.rakitiw_version }}_all_24.10.0.ipk

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          prerelease: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/*
          overwrite: true
          tag: ${{ needs.build_ipk.outputs.rakitiw_version }}
          file_glob: true
